# Generated by Django 5.2.4 on 2025-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("MPesa", "M-Pesa"),
                            ("Cash", "Cash"),
                        ],
                        default="Credit Card",
                        max_length=50,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
