# Generated by Django 5.2.4 on 2025-07-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_created_at_userprofile_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_profile", "Can view user profile"),
                    ("can_edit_profile", "Can edit user profile"),
                    ("can_delete_profile", "Can delete user profile"),
                    ("can_view_products", "Can view products"),
                    ("can_add_product", "Can add product"),
                    ("can_edit_product", "Can edit product"),
                    ("can_delete_product", "Can delete product"),
                    ("can_view_orders", "Can view orders"),
                    ("can_create_order", "Can create order"),
                    ("can_edit_order", "Can edit order"),
                    ("can_delete_order", "Can delete order"),
                    ("can_view_users", "Can view users"),
                    ("can_add_user", "Can add user"),
                    ("can_edit_user", "Can edit user"),
                    ("can_delete_user", "Can delete user"),
                ]
            },
        ),
    ]
