# Generated by Django 5.2.4 on 2025-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
