# Generated by Django 5.2.4 on 2025-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Shipping_address", models.CharField(max_length=255)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("shipping_date", models.DateTimeField(auto_now_add=True)),
                (
                    "Order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_info",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
