# Generated by Django 5.2.4 on 2025-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_rename_category_product_category_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True,
                default="product_images/default.jpg",
                null=True,
                upload_to="product_images/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
